apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: nginx-helm-2
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/cloud-prakhar/k8s-argo.git
    targetRevision: main

    # Location of your Helm chart
    path: helm/my-app

    helm:
      releaseName: nginx-helm-2

      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: demo-helm-2

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true